###
### This flowfile is intended to highlight capabilities of Liquibase Pro
### Review and update prior to use
###
### Liquibase version: 4.27.0+
###
### Liquibase sales: https://www.liquibase.com/contact-us
### Liquibase support: https://support.liquibase.com/knowledge
###

### 
### Prior to running the following files must exist in repository
###
### 1. liquibase.checks-settings.conf
###    Liquibase policy checks configuration file
###    https://docs.liquibase.com/liquibase-pro/policy-checks/home.html
###
### 2. changelog.main.xml
###    Root Liquibase changelog file
###    https://docs.liquibase.com/concepts/changelogs/home.html
###

###
### Global variables used in the flowfile
###
globalVariables:
  ###
  ### These variables are typically set via automation tools (see pipeline examples)
  ###
  ### LIQUIBASE_SEARCH_PATH: REQUIRED
  ### Use absolute paths when using Liquibase's Docker container
  ### LIQUIBASE_SEARCH_PATH: "/liquibase/changelog"
  ###
  ### LIQUIBASE_COMMAND_CHANGELOG_FILE: REQUIRED
  ### Root Liquibase changelog file
  ### LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog.main.xml"
  ###
  ### LB_BASE_DIR: REQUIRED
  ### The directory to write Liquibase output (e.g., logs, reports)
  ### LB_BASE_DIR: "/liquibase/changelogs"
  ###
  ### LB_ENVIRONMENT: REQUIRED
  ### LB_ENVIRONMENT should be the environment within the pipeline to operate on (e.g., DEV, UAT, PROD)
  ### LB_ENVIRONMENT: "DEV"
  ###
  ### Secrets: REQUIRED
  ### These values should be pulled from a secure vault via pipeline or Liquibase Pro extension
  ### https://docs.liquibase.com/tools-integrations/extensions/secrets-management/home.html
  ###
  ### LIQUIBASE_COMMAND_URL: "jdbc:h2:tcp://localhost:9090/mem:dev"
  ### LIQUIBASE_COMMAND_USERNAME: "dbuser"
  ### LIQUIBASE_COMMAND_PASSWORD: "letmein"
  ### LIQUIBASE_LICENSE_KEY: "12345"
  ###
  ### Structured logging
  ### Liquibase logs can be ingested by any standard observability tool (e.g., CloudWatch, Datadog, Elastic, Splunk)
  ### https://docs.liquibase.com/tools-integrations/observability/structured-logging.html
  ###
  ### LIQUIBASE_LOG_FILE: "liquibase.log.json"
  ### LIQUIBASE_LOG_FORMAT: "json"
  ### LIQUIBASE_LOG_LEVEL: "warning"
  ### LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: "false"
  ###
  ### Other settings
  ### LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: "issues"
  ### LIQUIBASE_SHOW_BANNER: "false"
  ###
  ### Files
  ###
  BASE_FLOW_FILE: "liquibase.flowfile.base.yaml"
  DIFF_FILE: "Diff_${LB_ENVIRONMENT}.json"
  ###
  ### Operational Reports
  ### Liquibase Pro creates operational reports for certain commands
  ### These reports can be copied to a shared location for distribution to users (e.g., S3)
  ### https://docs.liquibase.com/tools-integrations/observability/operation-reports.html
  ###
  CHECKS_REPORT: "Checks_${LB_ENVIRONMENT}.html"
  ###
  ### Workflow features
  ### Set these flags to T/F to turn Liquibase Pro features on/off
  ### These flags can also be set dynamically by an automation tool based on user input, environment, team, etc.
  ###
  LB_TEST_CHECKS: "${LB_TEST_CHECKS:-T}"

###
### Stages to execute
###
stages:
  Verify:
    actions:
      #
      # Execute base commands
      #
      - type: liquibase
        command: flow
        cmdArgs: { flow-file: "${BASE_FLOW_FILE}" }
  PolicyChecks:
    actions:
      #
      # Show policy checks
      # https://docs.liquibase.com/liquibase-pro/policy-checks/home.html
      #
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks show
        cmdArgs: { check-status: "enabled" }
      #
      # Run policy checks
      # https://docs.liquibase.com/liquibase-pro/policy-checks/home.html
      #
      - type: liquibase
        if: "${LB_TEST_CHECKS} == T"
        command: checks run
        cmdArgs: { report-enabled: "true", report-path: "${LB_BASE_DIR}", report-name: "${CHECKS_REPORT}", checks-scope: "changelog, database", changeset-filter: "pending", auto-update: "on" }